spring:
  main:
    banner-mode: off
  application:
    name: inventory-master
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

server:
  port: 8081
  servlet:
    context-path: /api
